## Auto generated for simulation simulator protos
load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "sim_mode_proto",
    srcs = ["sim_mode.proto"],
)

proto_library(
    name = "module_trigger_proto",
    srcs = ["module_trigger.proto"],
)

proto_library(
    name = "frame_meta_proto",
    srcs = ["frame_meta.proto"],
)

proto_library(
    name = "scenario_proto",
    srcs = ["scenario.proto"],
)

apollo_package()
