syntax = "proto2";

package apollo.simulation.simulator;

message PublisherInfo {
  optional string publisher_name = 1;
  repeated uint64 message_timestamps_ns = 2;
}

message SubscriberInfo {
  optional string subscriber_name = 1;
  repeated uint64 message_timestamps_ns = 2;
  repeated uint64 message_consumption_timestamps_ns = 3;
}

message FrameTaskMeta {
  optional string task_name = 1;
  optional uint64 start_timestamp_ns = 2;
  repeated PublisherInfo publisher_infos = 3;
  repeated SubscriberInfo subscriber_infos = 4;
}

message FrameMeta {
  repeated FrameTaskMeta tasks = 1;
}
