--flagfile=modules/common/data/global_flagfile.txt
--plot_size_buffer=0.2
--road_width_buffer=0.0
--task_manager_cycle_routing_num_gain=10
--task_manager_cycle_routing_max_effective_cycles=100
--task_manager_cycle_routing_cycles_per_command=0
--task_manager_cycle_routing_max_waypoints_per_command=5000
