## Auto generated for worldsim scenario proto
load("//tools:apollo_package.bzl", "apollo_package")
load("//tools/proto:proto.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "scenario_proto",
    srcs = ["scenario.proto"],
)

apollo_package()
