package(default_visibility = ["//visibility:public"])

filegroup(
    name = "cli_runtime",
    srcs = [
        "binary.py",
        "checks.py",
        "launcher.py",
        "task.py",
        "worker.py",
        "//modules/simulation/apps:execution_cli",
    ],
)
